### ISSUE TITLE
代码特征图不一致

### ISSUE THREAD

**Issue by EricHhha** [chongningni/CSVSR#2]
'''python
        # Pyramids
        for i in range(3, 0, -1):
            level = i-1
            self.offset_conv1[level] = nn.Conv2d(num_feat * 2, 18 * 8, 3, 1,
                                                 1)
            if i == 3:
                self.offset_conv2[level] = nn.Conv2d(18 * 8, 18 * 8, 3, 1,
                                                     1)
            else:
                self.offset_conv2[level] = nn.Conv2d(18 * 8 * 2, 18 * 8, 3,
                                                     1, 1)
                self.offset_conv3[level] = nn.Conv2d(18 * 8, 18 * 8, 3, 1,
                                                     1)
            self.dcn_pack[level] = ConvOffset2d(
                num_feat,
                num_feat,
                3,
                padding=1,
                num_deformable_groups = deformable_groups)

            if i < 3:
                self.feat_conv[level] = nn.Conv2d(num_feat * 2, num_feat, 3, 1,
                                                  1)

'''
这个里面self.dcn_pack[level]  的输入特征维度定义是 num_feat=64 而上面 offset_conv1=18*8 这两个特征维度不一致无法执行，请问定义模型是设置的num_feat=18*8 还是这个地方的特征图维度写的有问题

**Comment by chongningni** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    您好！本项目使用的可变形卷积与最新版本的可变形卷积存在一些差别，最新的可变形卷积都是在原可变形卷积的基础上进行了封装，如果您使用了最新的可变形卷积，18 * 8需要该为封装后可变形卷积的输入通道维度，如果你使用的本项目的可变形卷积，您可能需要安装本项目的可执行的环境，详细见Requirements。18*8(3*3*2*8)为offsets的维度数量，其中 3*3为卷积核的大小，2 代表两个方向上（x，y）的偏移self.dcn_pack[level] = ConvOffset2d(num_feat,num_feat,3,padding=1,num_deformable_groups = deformable_groups)self.dcn_pack的输入为原特征和偏移量offsets。offsets的通道维度和原特征的通道维度是不相同的，现阶段的比较新版本的可变形卷积offsets的通道输出为 num_feat 是因为最新的都是封装后的，在封装的函数里做了一个通道转换 （例如num_feat ->18*8）！您根据具体使用的《可变形卷积版本》的需要修改代码即可。希望本次解答能够为您提供帮助，祝好！
    
        
            
        
    
    
     
    
        
                    ***@***.***
        
    
 

  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2024年7月8日 16:39
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              [chongningni/CSVSR] 代码特征图不一致 (Issue #2)
        
      
    
  
  
'''python
# Pyramids
for i in range(3, 0, -1):
level = i-1
self.offset_conv1[level] = nn.Conv2d(num_feat * 2, 18 * 8, 3, 1,
1)
if i == 3:
self.offset_conv2[level] = nn.Conv2d(18 * 8, 18 * 8, 3, 1,
1)
else:
self.offset_conv2[level] = nn.Conv2d(18 * 8 * 2, 18 * 8, 3,
1, 1)
self.offset_conv3[level] = nn.Conv2d(18 * 8, 18 * 8, 3, 1,
1)
self.dcn_pack[level] = ConvOffset2d(
num_feat,
num_feat,
3,
padding=1,
num_deformable_groups = deformable_groups)
        if i < 3:
            self.feat_conv[level] = nn.Conv2d(num_feat * 2, num_feat, 3, 1,
                                              1)

'''
这个里面self.dcn_pack[level]  的输入特征维度定义是 num_feat=64 而上面 offset_conv1=188 这两个特征维度不一致无法执行，请问定义模型是设置的num_feat=188 还是这个地方的特征图维度写的有问题

**Comment by EricHhha** [comment]
非常感谢能收到您的回复！你的邮件对我帮助很大！再次对您致以诚挚的谢意！



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年07月08日 17:12 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>、State ***@***.***> |
| 主题 | Re: [chongningni/CSVSR] 代码特征图不一致 (Issue #2) |







font{
line-height: 1.6;
}
ul,ol{
padding-left: 20px;
list-style-position: inside;
}



您好！本项目使用的可变形卷积与最新版本的可变形卷积存在一些差别，最新的可变形卷积都是在原可变形卷积的基础上进行了封装，如果您使用了最新的可变形卷积，18 * 8需要该为封装后可变形卷积的输入通道维度，如果你使用的本项目的可变形卷积，您可能需要安装本项目的可执行的环境，详细见Requirements。18*8(3*3*2*8)为offsets的维度数量，其中 3*3为卷积核的大小，2 代表两个方向上（x，y）的偏移self.dcn_pack[level] = ConvOffset2d(num_feat,num_feat,3,padding=1,num_deformable_groups = deformable_groups)self.dcn_pack的输入为原特征和偏移量offsets。offsets的通道维度和原特征的通道维度是不相同的，现阶段的比较新版本的可变形卷积offsets的通道输出为 num_feat 是因为最新的都是封装后的，在封装的函数里做了一个通道转换 （例如num_feat ->18*8）！您根据具体使用的《可变形卷积版本》的需要修改代码即可。希望本次解答能够为您提供帮助，祝好！









***@***.***





---- 回复的原邮件 ----





发件人


***@***.***>





发送日期


2024年7月8日 16:39




收件人




***@***.***>






抄送人



***@***.***>






主题


[chongningni/CSVSR] 代码特征图不一致 (Issue #2)





'''python
# Pyramids
for i in range(3, 0, -1):
level = i-1
self.offset_conv1[level] = nn.Conv2d(num_feat * 2, 18 * 8, 3, 1,
1)
if i == 3:
self.offset_conv2[level] = nn.Conv2d(18 * 8, 18 * 8, 3, 1,
1)
else:
self.offset_conv2[level] = nn.Conv2d(18 * 8 * 2, 18 * 8, 3,
1, 1)
self.offset_conv3[level] = nn.Conv2d(18 * 8, 18 * 8, 3, 1,
1)
self.dcn_pack[level] = ConvOffset2d(
num_feat,
num_feat,
3,
padding=1,
num_deformable_groups = deformable_groups)
if i < 3:
self.feat_conv[level] = nn.Conv2d(num_feat * 2, num_feat, 3, 1,
1)

'''
这个里面self.dcn_pack[level] 的输入特征维度定义是 num_feat=64 而上面 offset_conv1=188 这两个特征维度不一致无法执行，请问定义模型是设置的num_feat=188 还是这个地方的特征图维度写的有问题
